- README.md
- autoload/multiple_cursors.vim
- doc/multiple_cursors.txt
- plugin/multiple_cursors.vim
VIM's * command searches for the whole word -- it wraps current word with word
boundaries: \< and \>. g*, on the other hand, does not care about word
boundaries.
This patch adds functionality to configure multiple cursors behaviour to be
consistent with VIM's * and g*. To do that, use newly introduced option:
let g:multi_cursor_start_key='g<C-n>'
let g:multi_cursor_start_word_key='<C-n>'
Note that in current implementation "start word" command works in both Normal
and Visual modes.
Fixes #104.
> Add support for searching whole words

- autoload/multiple_cursors.vim
My original fix here stopped the last cursor (the real one) from jumping back a
slot, but that's vim's default behaviour. Instead, move all the *other* cursors
back one manually.
Referenced from #95 as part of #102
> When switching insert->normal, backtrack cursors

- autoload/multiple_cursors.vim
This fixes a problem where if you use MultipleCursorFind, you don't get the _before function called
Wasn't sure how to write a test for this case, didn't look like the _before and _after functionality is tested in the specs.
I didn't see a CONTRIBUTING doc or anything, please let me know if there is anything I need to do to conform to this projects guidelines...
> Call Multiple_cursors_before with find

- autoload/multiple_cursors.vim
The check was not taking into account the mode, so values set in
g:multi_cursor_normal_maps were also (sort of) applying in visual mode.
Secondary change: call `s:display_error()` *before* resetting the cursor modes
or else the mode we check there now is wrong.
@faceleg @balta2ar as discussed tangentially in #111
> Fix a subtle bug in _normal_maps

- autoload/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
@balta2ar here's a test for a bug I just found while playing with this some more. Not entirely sure what the problem is. (It's a bit of a contrived scenario so it's probably not a big deal, but it's not how I would have expected it to behave).
To clarify: the `after` is what I would expect. The test is currently failing because it does something else.
> Add test for a newly discovered paste bug

- doc/multiple_cursors.txt
Fixed a typo ('keystroes' v 'keystrokes').
Apparently, also removed trailing whitespace as I forgot I have that setting on in Vim. If that's a problem, I can redo this PR.
> Fix typo in help text.

- README.md
- autoload/multiple_cursors.vim
- plugin/multiple_cursors.vim
I got bit by this, and agree it should be default behaviour. Should fix #129
> Quick stab at selecting word boundaries by defualt

- README.md
- autoload/multiple_cursors.vim
If you use https://github.com/Shougo/neobundle.vim, you can test with:
```viml
NeoBundle 'tony/vim-multiple-cursors', { 'rev': 'quit-multiple-cursors' }
```
Map quitting:
```viml
let g:multi_cursor_quit_key='<C-c>'
nnoremap <C-c> :call multiple_cursors#quit()<CR>
```
Originally was named "allow s:quit for multiple-cursors to be called publicly". Apparently, this will get ``<C-c>`` to work only if ``<C-c>`` is mapped, but there seems to be more interconnections inside that get in the way.
> Fix #27: allow <Ctrl-c> to quit highlight mode. Document in README.md

- README.md
- doc/multiple_cursors.txt
- plugin/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
I identified these multi-key mappings by going across the keyboard, row by row, and checking whether that key, or <kbd>Shift</kbd> plus that key, was a multi-key mapping by default.
I manually tested this change by removing the setting from my `vimrc` and making sure that the listed keys were still handled correctly, and that they weren’t when the dictionary was set to empty.
I first posted these values for `g:multi_cursor_normal_maps` in https://github.com/terryma/vim-multiple-cursors/issues/21#issuecomment-75443638.
> Set good defaults for g:multi_cursor_normal_maps

- spec/benchmark_spec.rb
Tests were failing because `spec/benchmark_spec.rb` was using a `before` method (defined in `spec/multiple_cursors_spec.rb`) which required `options` to be available to the context.
```
Multiple Cursors
#benchmark (FAILED - 1)
Multiple Cursors op pending & exit from insert|visual mode
#paste from unnamed register to 3 cursors
#paste buffer normal caw then p
#paste buffer normal C then ABC then p
#paste buffer normal daw then P
#paste buffer normal D then P
#paste buffer normal s then p
Multiple Cursors when normal_maps is empty
#normal mode 'd'
Multiple Cursors
#paste buffer normal x then p
#paste buffer visual y then p
#paste buffer initial visual y then P
#paste buffer visual y then P
#paste buffer visual Y then P
#multiline replacement
#single line replacement
#mixed line replacement …
```
> Fixed failing test in benchmark_spec

- autoload/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
Here's a potential fix for issue #55.
A more general solution might be possible by changing the `<Plug>(multiple-cursors-apply)` mappings to expression mappings and having `apply_user_input_next()` return an empty string - trying to resolve the issue of text being inserted into the buffer when `I` and `A` are pressed in Visual mode.
```VimL
inoremap <expr> <Plug>(multiple-cursors-apply) <SID>apply_user_input_next('i')
nnoremap <expr> <Plug>(multiple-cursors-apply) <SID>apply_user_input_next('n')
xnoremap <expr> <Plug>(multiple-cursors-apply) <SID>apply_user_input_next('v')
```
> Fix #55: make I and A work in Visual mode

- autoload/multiple_cursors.vim
With the below buffer contents, when you visually select lines 2-5 and execute `:'<,'>MultipleCursorFind text_to_find`, the real cursor will be positioned on line 8 (outside the search range) - if line 8 is moved down a few pages (outside the view of lines 2-5), then all virtual cursors will be off-screen.
```
" visually select the next four lines and execute `:'<,'>MultipleCursorFind text_to_find`
text_to_find
text_to_find
text_to_find
text_to_find
" the cursor will be positioned on the following line
text_to_find
```
This PR fixes the issue by repositioning the real cursor at the end of the previous match when it goes outside the search range.
> Keep cursor within range for MultipleCursorsFind

- autoload/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
s:get_text doesn't handle multi-byte strings.
before 
after
> fix issue that vim-multiple-cursor break multi-byte strings

- autoload/multiple_cursors.vim
Fixes #233 
'doautocmd User ...' is also invoked with 'silent' in plugins like NERDTree for instance.
Thanks a lot for this amazing plug-in !
Cheers,
An enthusiastic contributor
> Silence doautocmd to avoid the 'No matching autocommands' message

- autoload/multiple_cursors.vim
Updates where starting at index=size-1 and wrapping instead of starting at index=0
Then inserting cursors here and doing **backspace**:
```
|mon
|tue
|wed
```
You would loose the last cursor because cursor update was done in the order index=2, 0, 1 (see **s:CursorManager.update_current()**):
```
|mon|tuewed
```
This PR fixes it by updating cursors in the order index=0, 1, 2:
```
|mon|tue|wed
```
I did not notice any regression. It might fix #234: I observed a different behavior, but the issue description is a bit messy, so it is hard to see if it fixes the issue.
Please note that putting the cursor at the **end of the line** and pressing **del** is still flaky.
Nothing to do with my PR as it was already the case before, but I will try to tackle that when I have time.
Cheers,
Antoine
> Fix cursors update when number of lines changes

- autoload/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
We can now press Del in insert mode at EOL, which is a nice feature.
Changes in the original code were very superficial to make it work.
All tests pass on antoinemadec/vim-multiple-cursors del_eof's branch.
Cheers,
Antoine
> Fix <DEL> at End-Of-Line, add corresponding test

- README.md
This is a keyboard fix for the second demo:
Join (`J`) adds spaces between the letters by default. To accomplish this without spaces, you need to use `gJ`. Perhaps you have changed some settings or key combinations?
``` shell
J                       Join [count] lines, with a minimum of two lines.                             
Remove the indent and insert up to two spaces (see                           
below).  Fails when on the last line of the buffer.                          
If [count] is too big it is reduce to the number of                          
lines available.                                                             
v_J                                          
{Visual}J               Join the highlighted lines, with a minimum of two                            
lines. …
```
> Updated readme to reflect default settings

- autoload/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
Use ninrod's #207 PR and add:
- support for '\<command\>0' (e.g.: 'd0')
- tests checking '0' key is properly handled
*bundle exec rake* is passing.
Once merged, this closes #207 and #152 
Cheers,
Antoine
> Add '0' key support in normal mode

- autoload/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
Fixes #201 and #205 
Add support for 2+ chars {lhs} mapping as well.
E.g.:
`imap jan january`
Tests checking those features have been added.
*bundle exec rake* is passing.
Cheers,
Antoine
> Insert mapping: fix {rhs}=<Esc> mappings; add 2+ chars {lhs} support

- README.md
- autoload/multiple_cursors.vim
- doc/multiple_cursors.txt
- plugin/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
No need to add the first letter of your mappings in the ```g:multi_cursor_insert_maps``` variable anymore!
That means less manual steps and more fun for the user, thanks for the suggestion ;)
The handling of normal_maps and visual_maps seems to be trickier, so I did not touch it.
From what I understand their _maps variables not only can be used by the user, but also features default characters to be able to handle 'dw' kind of operation.
If you want to refactor them as well or if you have any suggestions for me, please do not hesitate.
*bundle exec rake* is passing.
Cheers,
Antoine
> Feature: remove g:multi_cursor_insert_maps as it is not needed anymore

- autoload/multiple_cursors.vim
Should fix #246
Having 'imap ii <Esc>' takes 'timeoutlen' ms to print i in insert mode in Vim.
We try to emulate the same behavior using sleep 1ms 'timeoutlen' times in our plugin.
How ever there some other operations done and overhead time to take into account at each loop iteration.
For that reason, we increase our time counter by 1.5 instead of 1.
> insert mapping loop was too long; handle multiple keywords in imap's

- autoload/multiple_cursors.vim
Fix #249 and #248 
```bundle exec rake``` passes
> Fix imap <expr>, i.e. when {rhs} is a function

- README.md
- autoload/multiple_cursors.vim
- doc/multiple_cursors.txt
- plugin/multiple_cursors.vim
Fix #151 
Add the following mappings in both **normal** and **visual**:
- ```<C-m><C-n>```: select all occurrence with word boundaries
- ```g<C-m><C-n>```: select all occurrence without word boundary
The prefix ```<C-m>``` was chosen because **m** is close from **n** and starts like **m**ultiple
The prefix ```<C-a>``` would have be better (like **a**ll) but it was already used to increment numbers.
@eapache @balta2ar , let me know what you think.
I have been using this feature for 2 days, and I must say it is extremely addictive :)
> Add select_all() to select all occurence of a word, map is <c-m><c-n>

- autoload/multiple_cursors.vim
We were skipping it if you exited multiple cursor mode via a `:` special
command. Now we're not.
@antoinemadec I played around with just calling `s:exit()` here since that seemed to be more correct and would result in fewer inconsistencies like this, but it ended up breaking more things for some reason.
> Ensure we call Multiple_cursors_after in all cases

- README.md
This is less intrusive that completely switching the 'selection' option to "inclusive". The setting is there for a reason; some users actually prefer this mode! (Unfortunately, this also makes it much harder for plugins to behave correctly.)
&lt;SoapBox&gt;
Of course, ideally the plugin would "just work" with any `'selection'` value. I tried to patch that in, but it's not trivial, and I think intricate knowledge of all the stored positions is needed; something which you as the author surely have, but I don't. Actually accounting for exclusive selections is easy; usually just a `:normal! h` to correct the cursor position, or in the worst case subtracting the byte length of the last captured character from the end column. I guess the majority of the Vim user base does not change this …
> Documentation: Offer different workaround for selection=exclusive via plugin hooks

- README.md
- doc/multiple_cursors.txt
- plugin/multiple_cursors.vim
- spec/multiple_cursors_spec.rb
From #286 Issue
Sadly i could not run the ruby tests on my machine, but i hope the commit still helps.
Also removing trailing whitespaces from README.md
> Changing defaults to g:multi_cursor_exit_from_insert_mode = 0

- README.md
Small typo fixed in the `README.md` file.
> Readme: Typo fix "muticursor"
